### ISSUE TITLE
RTMP推音频,在断开链接的时候回报这个错误直接闪退

### ISSUE THREAD

**Issue by ILoveLin** [printlybyte/AndroidPCMtoAAC_RTMP_RTSP#1]
2021-02-25 09:09:35.196 31640-1648/com.company.shenzhou E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.company.shenzhou, PID: 31640
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2450)
        at com.pedro.encoder.audio.AudioEncoder.getDataFromEncoderAPI21(AudioEncoder.java:144)
        at com.pedro.encoder.audio.AudioEncoder.inputPCMData(AudioEncoder.java:131)
        at com.pedro.rtplibrary.base.Camera3Base.inputPCMData(Camera3Base.java:809)
        at com.pedro.encoder.input.audio.MicrophoneManager$1.run(MicrophoneManager.java:73)
        at java.lang.Thread.run(Thread.java:929)

**Comment by ILoveLin** [comment]
我已经解决这个问题了，如果后续看到这个项目的小伙伴可以在GitHub上搜索rtmp-rtsp-stream-client-java
或者直接登入一下网址
[https://github.com/pedroSG94/rtmp-rtsp-stream-client-java](url)按照说明继承之后使用


以下代码仅发送音频的代码如下


`RtmpOnlyAudio rtmpOnlyAudio = new RtmpOnlyAudio(connectCheckerRtmp);

    if (rtmpOnlyAudio.prepareAudio()) {
      rtmpOnlyAudio.startStream("endpoint");
    }`
